{
 "title": "General Photobooth overview",
 "description": "All information about photobooth",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Transaction count each day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {service_name=\"photobooth\"}\n  |= \"Payment log: Transaction\"\n  |= \"Payment successful, but not printed yet\"\n  |~ \"2025-08-14 (0[3-9]|1[0-9]|2[0-3]):\\\\d{2}:\\\\d{2}\"\n  | regexp \"(?P<date>\\\\d{4}-\\\\d{2}-\\\\d{2})\"\n  | label_format date=\"{{.date}}\"\n  [1d]\n) or vector(0)\n",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Approximate prints remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prints_remaining unless (prints_remaining == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of prints remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prints_remaining_percent unless (prints_remaining_percent == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SumUp transactions that are paid, but nothing was printed. Probably refund is needed.  [Last 30 days]",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"}\n|= \"Payment log: Transaction\"\n| regexp \"Payment log: Transaction (?P<transaction_code>[A-Za-z0-9]+)\"\n| label_format transaction_code=\"{{ .transaction_code }}\"\n| line_format \"Transaction Code: {{ .transaction_code }}\""
    }
   ]
  },
  {
   "title": "All logs [Last 30 days]",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"} |= ``"
    }
   ]
  },
  {
   "title": "Critical errors [Last 30 days]",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"}\n|= \"Critical error\"\n| regexp `Critical error: (?P<reason>[^\\s]+)`",
     "legendFormat": "reason"
    }
   ]
  },
  {
   "title": "Error logs [Last 30 days]",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"} |= \"ERROR\""
    }
   ]
  }
 ]
}