{
 "title": "Photobooth",
 "description": "Photobooth",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Transaction count each day [Last 30 days]",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {service_name=\"photobooth\"}\n  |= \"Payment log: Transaction\"\n  |= \"Payment successful, but not printed yet\"\n  |~ \"2025-08-14 (0[3-9]|1[0-9]|2[0-3]):\\\\d{2}:\\\\d{2}\"\n  | regexp \"(?P<date>\\\\d{4}-\\\\d{2}-\\\\d{2})\"\n  | label_format date=\"{{.date}}\"\n  [1d]\n) or vector(0)\n",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Successful payments",
   "type": "logs",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"}\n|= \"Payment log: Transaction\"\n|= \"Payment successful, but not printed yet\"\n| regexp \"(?P<date>\\\\d{4}-\\\\d{2}-\\\\d{2}) (?P<time>\\\\d{2}:\\\\d{2}:\\\\d{2}) - Payment log: Transaction (?P<transaction_code>[A-Za-z0-9]+)\"\n| line_format \"{{ .date }} {{ .time }} | Transaction Code: {{ .transaction_code }}\""
    }
   ]
  },
  {
   "title": "Additional logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"}\n|= \"Payment card not accepted by terminal or insufficient funds.\"\n| regexp \"(?P<date>\\\\d{4}-\\\\d{2}-\\\\d{2}) (?P<time>\\\\d{2}:\\\\d{2}:\\\\d{2})\"\n| line_format \"{{ .date }} {{ .time }} | Payment card not accepted by the terminal or insufficient funds.\""
    },
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"}\n|= \"Payment started, but no one paid. Payment cancelled after 1 minute.\"\n| regexp \"(?P<date>\\\\d{4}-\\\\d{2}-\\\\d{2}) (?P<time>\\\\d{2}:\\\\d{2}:\\\\d{2})\"\n| line_format \"{{ .date }} {{ .time }} | Payment started, but no one paid. Transaction cancelled after 1 minute.\""
    },
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"}\n|= \"Payment terminal not working, could not initiate the payment\"\n| regexp \"(?P<date>\\\\d{4}-\\\\d{2}-\\\\d{2}) (?P<time>\\\\d{2}:\\\\d{2}:\\\\d{2})\"\n| line_format \"{{ .date }} {{ .time }} | Payment terminal not working, could not initiate the payment\""
    },
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"}\n|= \"Failed to print collage\"\n| regexp \"(?P<date>\\\\d{4}-\\\\d{2}-\\\\d{2}) (?P<time>\\\\d{2}:\\\\d{2}:\\\\d{2})\"\n| line_format \"{{ .date }} {{ .time }} | Printer not working, cannot print picture.\""
    },
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"}\n|= \"Critical error: photo_capture_failed\"\n| regexp \"(?P<date>\\\\d{4}-\\\\d{2}-\\\\d{2}) (?P<time>\\\\d{2}:\\\\d{2}:\\\\d{2})\"\n| line_format \"{{ .date }} {{ .time }} | Camera not working, cannot take picture.\""
    }
   ]
  },
  {
   "title": "Approximate prints remaining",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prints_remaining unless (prints_remaining == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of prints remaining",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prints_remaining_percent unless (prints_remaining_percent == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SumUp transactions that are paid, but nothing was printed. Probably refund is needed.  [Last 30 days]",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"}\n|= \"Payment log: Transaction\"\n| regexp \"Payment log: Transaction (?P<transaction_code>[A-Za-z0-9]+)\"\n| label_format transaction_code=\"{{ .transaction_code }}\"\n| line_format \"Transaction Code: {{ .transaction_code }}\""
    }
   ]
  }
 ]
}