{
 "title": "General Photobooth overview",
 "description": "All information about photobooth",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Successful transactions with successful print [Last 30 days]",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(max_over_time(transaction_state_total{state=\"print_successful\"}[$__interval] offset -1d)) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approximate prints remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prints_remaining unless (prints_remaining == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of prints remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prints_remaining_percent unless (prints_remaining_percent == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SumUp transactions that are paid, but nothing was printed. Probably refund is needed.  [Last 30 days]",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"} \n  |= \"Payment log: Transaction \" \n  | regexp \"Payment log: Transaction (?P<transaction_id>\\\\d+)\"\n  | line_format \"{{ .transaction_id }}\""
    }
   ]
  },
  {
   "title": "Critical errors [Last 30 days]",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(max_over_time(errors_total{type=\"payment_failed\"}[$__interval] offset -1d)) or vector(0)",
     "legendFormat": "payment_failed"
    },
    {
     "expr": "sum(max_over_time(errors_total{type=\"photo_capture_failed\"}[$__interval] offset -1d)) or vector(0)",
     "legendFormat": "photo_capture_failed"
    },
    {
     "expr": "sum(max_over_time(errors_total{type=\"collage_creation_failed\"}[$__interval] offset -1d)) or vector(0)",
     "legendFormat": "collage_creation_failed"
    },
    {
     "expr": "sum(max_over_time(errors_total{type=\"print_failed\"}[$__interval] offset -1d)) or vector(0)",
     "legendFormat": "collage_creation_failed"
    }
   ]
  },
  {
   "title": "Error logs [Last 30 days]",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "All logs [Last 30 days]",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"photobooth\"} |= ``"
    }
   ]
  }
 ]
}